#  !/usr/bin/env python
#   -*- coding: utf-8 -*-
#
#  MethodEditorAboutDialog.py
#
#  This file is part of GunShotMatch
#
#  Copyright © 2019-2020 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# generated by wxGlade 0.9.3 on Sun Mar 29 15:37:56 2020
#

# 3rd party
import wx

# this package
from GuiV2.icons import get_icon


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MethodEditorAboutDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		"""
		:param parent: Can be None, a frame or another dialog box.
		:type parent: wx.Window
		:param id: An identifier for the dialog. A value of -1 is taken to mean a default.
		:type id: wx.WindowID
		:param title: The title of the dialog.
		:type title: str
		:param pos: The dialog position. The value DefaultPosition indicates a
		default position, chosen by either the windowing system or wxWidgets,
		depending on platform.
		:type pos: wx.Point
		:param size: The dialog size. The value DefaultSize indicates a default
		size, chosen by either the windowing system or wxWidgets, depending on
		platform.
		:type size: wx.Size
		:param style: The window style.
		:type style: int
		:param name: Used to associate a name with the window, allowing the
		application user to set Motif resource values for individual dialog boxes.
		:type name: str
		"""
		
		# begin wxGlade: MethodEditorAboutDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((400, 320))

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MethodEditorAboutDialog.__set_properties
		self.SetTitle("About")
		self.SetSize((400, 320))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MethodEditorAboutDialog.__do_layout
		main_sizer = wx.BoxSizer(wx.VERTICAL)
		main_sizer.Add((20, 20), 0, 0, 0)
		meth_editor_icon = wx.StaticBitmap(self, wx.ID_ANY, get_icon("method-editor", 64))
		main_sizer.Add(meth_editor_icon, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 3)
		meth_editor_label = wx.StaticText(self, wx.ID_ANY, "GunShotMatch Method Editor", style=wx.ALIGN_CENTER)
		meth_editor_label.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
		main_sizer.Add(meth_editor_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.EXPAND | wx.TOP, 3)
		version_label = wx.StaticText(self, wx.ID_ANY, "Version <version string goes here>", style=wx.ALIGN_CENTER)
		main_sizer.Add(version_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)
		copyright_label = wx.StaticText(self, wx.ID_ANY, u"Copyright © 2019-2020\nDominic Davis-Foster\nAll rights reserved.", style=wx.ALIGN_CENTER)
		main_sizer.Add(copyright_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 20)
		self.SetSizer(main_sizer)
		self.Layout()
		# end wxGlade
	
		btns = self.CreateStdDialogButtonSizer(wx.OK)
		main_sizer.Add(btns, 0, wx.ALIGN_RIGHT | wx.ALIGN_BOTTOM)
		self.SetSizer(main_sizer)
		self.Layout()

# end of class MethodEditorAboutDialog
