#  !/usr/bin/env python
#   -*- coding: utf-8 -*-
#
#  AmmoDetailsEditor_GUI.py
#
#  This file is part of GunShotMatch
#
#  Copyright © 2019-2020 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
# generated by wxGlade 0.9.0 on Thu Feb  7 18:16:22 2019
#

__author__ = "Dominic Davis-Foster"
__copyright__ = "Copyright 2019-2020 Dominic Davis-Foster"

__license__ = "GPLv3"
__version__ = "0.2.0"
__email__ = "dominic@davis-foster.co.uk"


# stdlib
import sys

# this package
sys.path.append("..")
from GuiV2.GSMatch2_Core import Ammunition
from GuiV2.GSMatch2_Core.launcher_tools import launch_app, SimpleLauncher


def main():
	return launch_app(
			name="Ammo Details Editor",
			pidname="AmmoDetailsEditor",
			appid="GunShotMatchAmmoDetailsEditor",
			wxapp=SimpleLauncher,
			gui_class=Ammunition.DetailsEditor,
			redirect=False)


if __name__ == "__main__":
	sys.exit(main())
