#  !/usr/bin/env python
#   -*- coding: utf-8 -*-
#
#  GunShotMatch_GUIv2.py
#
#  This file is part of GunShotMatch
#
#  Copyright © 2019-2020 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
# generated by wxGlade 0.9.0 on Thu Feb  7 18:16:22 2019
#

__author__ = "Dominic Davis-Foster"
__copyright__ = "Copyright 2019-2020 Dominic Davis-Foster"

__license__ = "GPLv3"
__version__ = "0.2.0"
__email__ = "dominic@davis-foster.co.uk"

# stdlib
import sys

# 3rd party
import wx

# this package
sys.path.append("..")
from GuiV2.GSMatch2_Core.Config import internal_config
from GuiV2.GSMatch2_Core.GUI import WelcomeDialog
from GuiV2.GSMatch2_Core.GunShotMatch import GunShotMatch
from GuiV2.GSMatch2_Core.launcher_tools import launch_app


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class GSM_App(wx.App):
	def OnInit(self):
		
		self.filename = None
		
		if internal_config.show_welcome_dialog:
			if internal_config.last_position != (-1, -1):
				self.show_welcome_dialog(pos=internal_config.last_position)
			else:
				self.show_welcome_dialog()
			if internal_config.exit_on_closing_welcome_dialog and not self.filename:
				return True
		
		self.GunShotMatch = GunShotMatch(None, wx.ID_ANY)
		
		if self.filename:
			self.GunShotMatch.open_project(self.filename)

		self.SetTopWindow(self.GunShotMatch)
		self.GunShotMatch.Show()
		
		return True
	
	def show_welcome_dialog(self, *args, **kwargs):
		with WelcomeDialog(None, wx.ID_ANY, *args, **kwargs) as dlg:
			# dlg.CenterOnScreen(wx.VERTICAL)
			val = dlg.ShowModal()
			
			if val == wx.ID_OK:
				selected_project = dlg.selected_project
				dlg.Destroy()
				self.filename = selected_project
			else:
				dlg.Destroy()

# end of class GSM_App


def main():
	return launch_app(
			name="GunShotMatch_GUIv2",
			pidname="GunShotMatch",
			appid="GunShotMatchGUI",
			wxapp=GSM_App,
			redirect=False)


if __name__ == "__main__":
	sys.exit(main())
