#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  MultipleExperimentSorterPanel.py
"""
wx.Panel for the MultipleExperimenttsDialog containing a wx.ListCtrl
	that can be sorted by clicking the column headers
"""
#
#  This file is part of GunShotMatch
#
#  Copyright (c) 2019  Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# generated by wxGlade 0.9.3 on Tue Dec  3 16:09:23 2019
#

import wx

from GuiV2.GSMatch2_Core import SorterPanels

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MultipleExperimentSorterPanel(SorterPanels.ExperimentSorterPanel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MultipleExperimentSorterPanel.__init__
		kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.expr_list = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)

		self.__set_properties()
		self.__do_layout()
		# end wxGlade
		self._itemDataMap = {}
		self.default_column_headers = ["Name", "Filename", "Description", "Method", "Original Filename", "Original Filetype"]

	def __set_properties(self):
		# begin wxGlade: MultipleExperimentSorterPanel.__set_properties
		self.expr_list.AppendColumn(u"Name ⭡", format=wx.LIST_FORMAT_LEFT, width=200)
		self.expr_list.AppendColumn("Filename", format=wx.LIST_FORMAT_LEFT, width=200)
		self.expr_list.AppendColumn("Description", format=wx.LIST_FORMAT_LEFT, width=200)
		self.expr_list.AppendColumn("Method", format=wx.LIST_FORMAT_LEFT, width=200)
		self.expr_list.AppendColumn("Original Filename", format=wx.LIST_FORMAT_LEFT, width=400)
		self.expr_list.AppendColumn("Original Filetype", format=wx.LIST_FORMAT_LEFT, width=150)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MultipleExperimentSorterPanel.__do_layout
		expr_list_sizer = wx.GridSizer(1, 1, 0, 0)
		expr_list_sizer.Add(self.expr_list, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND | wx.LEFT | wx.TOP, 5)
		self.SetSizer(expr_list_sizer)
		expr_list_sizer.Fit(self)
		self.Layout()
		# end wxGlade

# end of class MultipleExperimentSorterPanel
