#  !/usr/bin/env python
#   -*- coding: utf-8 -*-
#
#  filename.py
#
#  This file is part of GunShotMatch
#
#  Copyright (c) 2019  Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

#  !/usr/bin/env python
#   -*- coding: utf-8 -*-
#
#  StartupDialog.py
#
#  This file is part of GunShotMatch
#
#
#  GunShotMatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  GunShotMatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# generated by wxGlade 0.9.3 on Tue Nov 26 10:17:30 2019


# stdlib

# 3rd party
import wx
import wx.grid
import wx.html

# this package


class StartupDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: StartupDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((500, 325))
		self.main_panel = wx.Panel(self, wx.ID_ANY)
		self.new_project_radio = wx.RadioButton(self.main_panel, wx.ID_ANY, "Create new project", style=wx.RB_GROUP)
		self.open_existing_radio = wx.RadioButton(self.main_panel, wx.ID_ANY, "Open existing project")
		self.open_recent_radio = wx.RadioButton(self.main_panel, wx.ID_ANY, "Open recent project")
		self.recent_project_panel = wx.Panel(self.main_panel, wx.ID_ANY)
		self.recent_project_choice = wx.Choice(self.recent_project_panel, wx.ID_ANY, choices=["choice 1"])
		self.show_dialog_checkbox = wx.CheckBox(self.main_panel, wx.ID_ANY, "Show this dialog at startup")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: StartupDialog.__set_properties
		self.SetTitle("Startup")
		self.SetSize((500, 325))
		self.new_project_radio.SetValue(1)
		self.recent_project_choice.SetMinSize((200, 33))
		self.recent_project_choice.SetSelection(0)
		self.recent_project_panel.SetMaxSize((-1, 40))
		self.show_dialog_checkbox.SetValue(1)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: StartupDialog.__do_layout
		outer_sizer = wx.BoxSizer(wx.HORIZONTAL)
		main_sizer = wx.BoxSizer(wx.VERTICAL)
		options_box_sizer = wx.StaticBoxSizer(wx.StaticBox(self.main_panel, wx.ID_ANY, "Options"), wx.VERTICAL)
		options_grid_sizer = wx.BoxSizer(wx.HORIZONTAL)
		welcome_label = wx.StaticText(self.main_panel, wx.ID_ANY, "Welcome to GunShotMatch")
		welcome_label.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
		main_sizer.Add(welcome_label, 0, wx.BOTTOM, 5)
		intro_label = wx.StaticText(self.main_panel, wx.ID_ANY, "Select one of the options below and click OK to start.")
		main_sizer.Add(intro_label, 0, wx.LEFT, 20)
		static_line_1 = wx.StaticLine(self.main_panel, wx.ID_ANY)
		main_sizer.Add(static_line_1, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 6)
		options_box_sizer.Add(self.new_project_radio, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
		options_box_sizer.Add(self.open_existing_radio, 1, wx.BOTTOM | wx.LEFT, 5)
		options_box_sizer.Add(self.open_recent_radio, 1, wx.LEFT, 5)
		label_1 = wx.StaticText(self.recent_project_panel, wx.ID_ANY, "Select recent project:")
		options_grid_sizer.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.LEFT, 20)
		options_grid_sizer.Add(self.recent_project_choice, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.LEFT, 10)
		self.recent_project_panel.SetSizer(options_grid_sizer)
		options_box_sizer.Add(self.recent_project_panel, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.EXPAND | wx.LEFT, 5)
		main_sizer.Add(options_box_sizer, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
		main_sizer.Add(self.show_dialog_checkbox, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
		static_line_2 = wx.StaticLine(self.main_panel, wx.ID_ANY)
		main_sizer.Add(static_line_2, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 6)
		self.main_panel.SetSizer(main_sizer)
		outer_sizer.Add(self.main_panel, 1, wx.ALL | wx.EXPAND, 5)
		self.SetSizer(outer_sizer)
		self.Layout()
		# end wxGlade
		
		btnsizer = wx.StdDialogButtonSizer()
		
		btn = wx.Button(self, wx.ID_OK)
		btn.SetDefault()
		btnsizer.AddButton(btn)
		
		btn = wx.Button(self, wx.ID_CANCEL)
		btnsizer.AddButton(btn)
		
		# btn = wx.Button(self, wx.ID_HELP)
		# btnsizer.AddButton(btn)
		
		btnsizer.Realize()
		
		main_sizer.Add(btnsizer, 0, wx.ALIGN_RIGHT | wx.EXPAND | wx.TOP, 5)

# end of class StartupDialog
