#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
#  Copyright (c) 2017-2019 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
# generated by wxGlade 0.9.0 on Thu Feb  7 18:16:22 2019
#

__author__ = "Dominic Davis-Foster"
__copyright__ = "Copyright 2017-2019 Dominic Davis-Foster"

__license__ = "GPLv3"
__version__ = "0.2.0"
__email__ = "dominic@davis-foster.co.uk"

import sys
sys.path.append("..")

import re
import os
import wx
import time
import traceback
import threading
import subprocess

from GSMatch.GSMatch_Core.thread_boilerplates import EventBoilerplate as ProjectEvent
from GSMatch.GSMatch_Core.thread_boilerplates import EventBoilerplate as ConversionEvent
from GSMatch.GSMatch_Core.thread_boilerplates import LogEventBoilerplate as ProjectLogEvent
from GSMatch.GSMatch_Core.thread_boilerplates import LogEventBoilerplate as ConversionLogEvent

import wx.html2
import wx.richtext
from wx.adv import NotificationMessage

import matplotlib

from GSMatch.GSMatch_Core import Launcher


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class GSM_App(wx.App):
	def OnInit(self):
		self.frame = Launcher.Launcher(None, wx.ID_ANY, "")
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True

# end of class GSM_App

if __name__ == "__main__":
	print("###")
	print(wx.Colour(wx.SYS_COLOUR_BACKGROUND))
	print(wx.Colour(240, 240, 240))
	print("###")
	
	if sys.platform == "win32":
		import ctypes
		myappid = "GunShotMatchGUI"
		ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
		
	GunShotMatch = GSM_App(False)
	GunShotMatch.MainLoop()

	print("Goodbye :)")
	
	sys.exit(0)
