# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Fri May 10 17:05:01 2019
#

import wx
import wx.html2
from utils.wxTools import file_dialog
from gsm_core import pretty_name_from_info
from gsm_gui.threads import ComparisonThread, EVT_COMPARISON, EVT_COMPARISON_LOG
import configparser as ConfigParser
from gsm_gui import ChartViewer
from gsm_gui.utils import get_toolbar_icon


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class compare_tab(wx.Panel):
	def __init__(self, parent, *args, **kwds):
		self._parent = parent
		# begin wxGlade: compare_tab.__init__
		kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.comparison_panel = wx.Panel(self, wx.ID_ANY)
		self.comparison_left_picker = wx.TextCtrl(self.comparison_panel, wx.ID_ANY, "", style=wx.TE_READONLY)
		self.comparison_left_browse_btn = wx.BitmapButton(self.comparison_panel, wx.ID_ANY, get_toolbar_icon("ART_FILE_OPEN", 16))
		self.comparison_left_header = wx.html2.WebView.New(self.comparison_panel, wx.ID_ANY)
		self.comparison_right_picker = wx.TextCtrl(self.comparison_panel, wx.ID_ANY, "", style=wx.TE_READONLY)
		self.comparison_right_browse_btn = wx.BitmapButton(self.comparison_panel, wx.ID_ANY, get_toolbar_icon("ART_FILE_OPEN", 16))
		self.comparison_right_header = wx.html2.WebView.New(self.comparison_panel, wx.ID_ANY)
		self.comparison_alignment_Dw_value = wx.SpinCtrlDouble(self.comparison_panel, wx.ID_ANY, "0.0", min=0.0, max=99.0)
		self.comparison_alignment_Dw_value.SetDigits(2)
		self.comparison_alignment_Gw_value = wx.SpinCtrlDouble(self.comparison_panel, wx.ID_ANY, "0.0", min=0.0, max=99.0)
		self.comparison_alignment_Gw_value.SetDigits(2)
		self.comparison_alignment_min_peaks_value = wx.SpinCtrlDouble(self.comparison_panel, wx.ID_ANY, "0.0", min=0.0, max=99.0)
		self.significance_level_value = wx.SpinCtrlDouble(self.comparison_panel, wx.ID_ANY, "0.05", min=0.0, max=1.0)
		self.significance_level_value.SetDigits(3)
		self.comparison_apply_btn = wx.Button(self.comparison_panel, wx.ID_ANY, "Apply")
		self.comparison_default_btn = wx.Button(self.comparison_panel, wx.ID_ANY, "Default")
		self.comparison_reset_btn = wx.Button(self.comparison_panel, wx.ID_ANY, "Reset")
		self.run_comparison_button = wx.Button(self.comparison_panel, wx.ID_ANY, u"▶ Run Comparison")
		self.comparison_radar_button = wx.Button(self.comparison_panel, wx.ID_ANY, "Radar Chart")
		self.comparison_mean_pa_button = wx.Button(self.comparison_panel, wx.ID_ANY, "Mean Peak Area")
		self.comparison_box_whisker_btn = wx.Button(self.comparison_panel, wx.ID_ANY, "Box Whisker Plot")
		self.comparison_pca_btn = wx.Button(self.comparison_panel, wx.ID_ANY, "")
		self.comparison_log_text_control = wx.TextCtrl(self.comparison_panel, wx.ID_ANY, "", style=wx.TE_CHARWRAP | wx.TE_MULTILINE | wx.TE_READONLY)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.on_left_comparison_browse, self.comparison_left_browse_btn)
		self.Bind(wx.EVT_BUTTON, self.on_right_comparison_browse, self.comparison_right_browse_btn)
		self.Bind(wx.EVT_BUTTON, self.comparison_run, self.run_comparison_button)
		# end wxGlade
	
		self.Bind(wx.EVT_BUTTON, self.do_comparison_apply, self.comparison_apply_btn)
		self.Bind(wx.EVT_BUTTON, self.do_comparison_default, self.comparison_default_btn)
		self.Bind(wx.EVT_BUTTON, self.do_comparison_reset, self.comparison_reset_btn)
		self.Bind(wx.EVT_BUTTON, self.comparison_show_radar, self.comparison_radar_button)
		self.Bind(wx.EVT_BUTTON, self.comparison_show_box_whisker, self.comparison_box_whisker_btn)
		self.Bind(wx.EVT_BUTTON, self.comparison_show_mean_peak_area, self.comparison_mean_pa_button)
		self.Bind(wx.EVT_BUTTON, self.comparison_show_pca, self.comparison_pca_btn)
		
		#self.Bind(EVT_COMPARISON, self.OnComparisonDone)
		self.Bind(EVT_COMPARISON_LOG, self.OnComparisonLog)
		
		self.comparison_right_project = None
		self.comparison_right_project_name = None
		self.comparison_left_project = None
		self.comparison_left_project_name = None
		
		log_font = wx.Font(12, wx.FONTFAMILY_TELETYPE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "FreeMono")
		self.comparison_log_text_control.SetFont(log_font)
		
		self.do_comparison_reset()

	def __set_properties(self):
		# begin wxGlade: compare_tab.__set_properties
		self.comparison_left_picker.SetMinSize((171, -1))
		self.comparison_left_browse_btn.SetMinSize((29, 29))
		self.comparison_left_header.SetMinSize((200, 160))
		self.comparison_right_picker.SetMinSize((171, -1))
		self.comparison_right_browse_btn.SetMinSize((29, 29))
		self.comparison_right_header.SetMinSize((200, 160))
		self.comparison_alignment_Dw_value.SetMinSize((120, 29))
		self.comparison_alignment_Dw_value.SetIncrement(0.01)
		self.comparison_alignment_Gw_value.SetMinSize((120, 29))
		self.comparison_alignment_Gw_value.SetIncrement(0.01)
		self.comparison_alignment_min_peaks_value.SetMinSize((120, 29))
		self.significance_level_value.SetIncrement(0.001)
		self.run_comparison_button.Enable(False)
		self.comparison_radar_button.Enable(False)
		self.comparison_mean_pa_button.Enable(False)
		self.comparison_box_whisker_btn.Enable(False)
		self.comparison_pca_btn.Enable(False)
		self.comparison_pca_btn.SetLabel("Principal\nComponent\nAnalysis")
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: compare_tab.__do_layout
		comparison_parent_sizer = wx.BoxSizer(wx.VERTICAL)
		comparison_sizer = wx.BoxSizer(wx.HORIZONTAL)
		comparison_log_sizer = wx.BoxSizer(wx.VERTICAL)
		comparison_option_sizer = wx.BoxSizer(wx.VERTICAL)
		comparison_settings_grid = wx.FlexGridSizer(1, 3, 10, 10)
		comparison_button_sizer = wx.BoxSizer(wx.VERTICAL)
		comparison_settings_sizer = wx.BoxSizer(wx.VERTICAL)
		comparison_settings_button_sizer = wx.BoxSizer(wx.HORIZONTAL)
		comparison_alignment_grid = wx.FlexGridSizer(3, 2, 0, 0)
		comparison_alignment_Dw_sizer = wx.BoxSizer(wx.HORIZONTAL)
		comparison_pickers_grid = wx.FlexGridSizer(1, 3, 10, 10)
		comparison_right = wx.BoxSizer(wx.VERTICAL)
		comparison_right_picker_sizer = wx.BoxSizer(wx.HORIZONTAL)
		comparison_left = wx.BoxSizer(wx.VERTICAL)
		comparison_left_picker_sizer = wx.BoxSizer(wx.HORIZONTAL)
		comparison_left_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Compare these Samples...", style=wx.ALIGN_LEFT)
		comparison_left.Add(comparison_left_label, 0, 0, 25)
		comparison_left_picker_sizer.Add(self.comparison_left_picker, 0, 0, 0)
		comparison_left_picker_sizer.Add(self.comparison_left_browse_btn, 0, 0, 0)
		comparison_left.Add(comparison_left_picker_sizer, 0, wx.BOTTOM | wx.TOP, 5)
		comparison_left.Add(self.comparison_left_header, 0, wx.EXPAND, 5)
		comparison_pickers_grid.Add(comparison_left, 1, wx.EXPAND, 0)
		comparison_picker_v_line = wx.StaticLine(self.comparison_panel, wx.ID_ANY, style=wx.LI_VERTICAL)
		comparison_pickers_grid.Add(comparison_picker_v_line, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
		comparison_right_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "... To These Samples", style=wx.ALIGN_LEFT)
		comparison_right.Add(comparison_right_label, 0, 0, 25)
		comparison_right_picker_sizer.Add(self.comparison_right_picker, 0, 0, 0)
		comparison_right_picker_sizer.Add(self.comparison_right_browse_btn, 0, 0, 0)
		comparison_right.Add(comparison_right_picker_sizer, 0, wx.BOTTOM | wx.TOP, 5)
		comparison_right.Add(self.comparison_right_header, 0, wx.EXPAND, 5)
		comparison_pickers_grid.Add(comparison_right, 1, wx.EXPAND, 0)
		comparison_option_sizer.Add(comparison_pickers_grid, 1, wx.EXPAND, 10)
		static_line_3 = wx.StaticLine(self.comparison_panel, wx.ID_ANY)
		comparison_option_sizer.Add(static_line_3, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
		comparison_settings_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Settings")
		comparison_settings_label.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
		comparison_settings_sizer.Add(comparison_settings_label, 0, 0, 0)
		comparison_alignment_top_text = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Dynamic Peak Alignment")
		comparison_alignment_top_text.SetToolTip("Settings for PyMS Dynamic Peak Alignment")
		comparison_settings_sizer.Add(comparison_alignment_top_text, 0, wx.TOP, 5)
		comparison_alignment_Dw_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "RT Modulation: ")
		comparison_alignment_grid.Add(comparison_alignment_Dw_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		comparison_alignment_Dw_sizer.Add(self.comparison_alignment_Dw_value, 0, 0, 0)
		comparison_alignment_Dw_label_2 = wx.StaticText(self.comparison_panel, wx.ID_ANY, " s", style=wx.ALIGN_LEFT)
		comparison_alignment_Dw_sizer.Add(comparison_alignment_Dw_label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		comparison_alignment_grid.Add(comparison_alignment_Dw_sizer, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		comparison_alignment_Gw_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Gap Penalty: ")
		comparison_alignment_grid.Add(comparison_alignment_Gw_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		comparison_alignment_grid.Add(self.comparison_alignment_Gw_value, 0, 0, 0)
		comparison_alignment_min_peaks_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Min Peaks: ")
		comparison_alignment_grid.Add(comparison_alignment_min_peaks_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		comparison_alignment_grid.Add(self.comparison_alignment_min_peaks_value, 0, 0, 0)
		comparison_settings_sizer.Add(comparison_alignment_grid, 1, wx.ALL | wx.EXPAND, 5)
		significance_level_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, u"Significance Level (α): ")
		comparison_settings_sizer.Add(significance_level_label, 0, wx.BOTTOM | wx.TOP, 5)
		comparison_settings_sizer.Add(self.significance_level_value, 0, 0, 0)
		comparison_line_4 = wx.StaticLine(self.comparison_panel, wx.ID_ANY)
		comparison_settings_sizer.Add(comparison_line_4, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
		comparison_settings_button_sizer.Add(self.comparison_apply_btn, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.RIGHT, 9)
		comparison_settings_button_sizer.Add(self.comparison_default_btn, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.RIGHT, 9)
		comparison_settings_button_sizer.Add(self.comparison_reset_btn, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.RIGHT, 9)
		comparison_settings_sizer.Add(comparison_settings_button_sizer, 1, wx.ALIGN_RIGHT, 20)
		comparison_settings_grid.Add(comparison_settings_sizer, 1, wx.EXPAND, 0)
		static_line_8 = wx.StaticLine(self.comparison_panel, wx.ID_ANY, style=wx.LI_VERTICAL)
		comparison_settings_grid.Add(static_line_8, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
		comparison_button_sizer.Add(self.run_comparison_button, 0, 0, 0)
		static_line_2 = wx.StaticLine(self.comparison_panel, wx.ID_ANY)
		comparison_button_sizer.Add(static_line_2, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
		comparison_charts_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Charts")
		comparison_charts_label.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
		comparison_button_sizer.Add(comparison_charts_label, 0, wx.BOTTOM, 5)
		comparison_button_sizer.Add(self.comparison_radar_button, 0, wx.BOTTOM | wx.LEFT, 3)
		comparison_button_sizer.Add(self.comparison_mean_pa_button, 0, wx.BOTTOM | wx.LEFT, 3)
		comparison_button_sizer.Add(self.comparison_box_whisker_btn, 0, wx.BOTTOM | wx.LEFT, 3)
		comparison_button_sizer.Add(self.comparison_pca_btn, 0, wx.BOTTOM | wx.LEFT, 3)
		comparison_settings_grid.Add(comparison_button_sizer, 1, wx.EXPAND, 0)
		comparison_option_sizer.Add(comparison_settings_grid, 2, wx.EXPAND | wx.LEFT, 10)
		comparison_sizer.Add(comparison_option_sizer, 1, wx.EXPAND | wx.RIGHT, 10)
		comparison_log_line = wx.StaticLine(self.comparison_panel, wx.ID_ANY, style=wx.LI_VERTICAL)
		comparison_sizer.Add(comparison_log_line, 0, wx.EXPAND, 0)
		comparison_log_label = wx.StaticText(self.comparison_panel, wx.ID_ANY, "Log:")
		comparison_log_sizer.Add(comparison_log_label, 0, wx.BOTTOM, 5)
		comparison_log_sizer.Add(self.comparison_log_text_control, 4, wx.EXPAND | wx.RIGHT, 10)
		comparison_sizer.Add(comparison_log_sizer, 3, wx.ALL | wx.EXPAND, 10)
		self.comparison_panel.SetSizer(comparison_sizer)
		comparison_parent_sizer.Add(self.comparison_panel, 7, wx.ALL | wx.EXPAND, 10)
		self.SetSizer(comparison_parent_sizer)
		comparison_parent_sizer.Fit(self)
		self.Layout()
		# end wxGlade

	
	def on_left_comparison_browse(self, event):  # wxGlade: compare_tab.<event_handler>
		selected_project = file_dialog(self, "info", "Choose a Project to Open", "info files",
									   style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST,
									   # defaultDir=self.Config.get("main", "resultspath"))
									   defaultDir=self._parent.Config.RESULTS_DIRECTORY)
		if selected_project == None:
			return
		
		if pretty_name_from_info(selected_project) == self.comparison_right_project_name:
			wx.MessageBox("You cannot compare a project to itself!\nPlease choose a different project.", "Error",
						  wx.ICON_ERROR | wx.OK)
			return
		
		self.comparison_left_project = selected_project
		self.comparison_left_project_name = pretty_name_from_info(self.comparison_left_project)
		
		self.comparison_left_picker.SetValue(self.comparison_left_project_name)
		self.comparison_left_header.LoadURL("file://{}".format(self.comparison_left_project))
		
		self.comparison_check_enable()
	
	def on_right_comparison_browse(self, event):  # wxGlade: compare_tab.<event_handler>
		selected_project = file_dialog(self, "info", "Choose a Project to Open", "info files",
									   style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST,
									   # defaultDir=self.Config.get("main", "resultspath"))
									   defaultDir=self._parent.Config.RESULTS_DIRECTORY)
		if selected_project == None:
			return
		
		if pretty_name_from_info(selected_project) == self.comparison_left_project_name:
			wx.MessageBox("You cannot compare a project to itself!\nPlease choose a different project.", "Error",
						  wx.ICON_ERROR | wx.OK)
			return
		
		self.comparison_right_project = selected_project
		self.comparison_right_project_name = pretty_name_from_info(self.comparison_right_project)
		
		self.comparison_right_picker.SetValue(self.comparison_right_project_name)
		self.comparison_right_header.LoadURL("file://{}".format(self.comparison_right_project))
		
		self.comparison_check_enable()
	
	def comparison_check_enable(self):
		if self.comparison_right_project and self.comparison_left_project:
			self.run_comparison_button.Enable()
			self.comparison_box_whisker_btn.Enable()
			self.comparison_pca_btn.Enable()
			self.comparison_mean_pa_button.Enable()
			self.comparison_radar_button.Enable()
	
	def comparison_run(self, event):  # wxGlade: compare_tab.<event_handler>
		a_value = self.significance_level_value.GetValue()
		
		self.comparison = ComparisonThread(self,
										   self.comparison_left_project,
										   self.comparison_right_project,
										   self._parent.Config,
										   a_value)
		self.comparison.start()
	
	def do_comparison_apply(self, event):  # wxGlade: Launcher.<event_handler>
		# Save the settings
		self._parent.Config.comparison_a = self.significance_level_value.GetValue()
		self._parent.Config.comparison_rt_modulation = self.comparison_alignment_Dw_value.GetValue()
		self._parent.Config.comparison_gap_penalty = self.comparison_alignment_Gw_value.GetValue()
		self._parent.Config.comparison_min_peaks = int(self.comparison_alignment_min_peaks_value.GetValue())
		
		print("Event handler 'do_comparison_apply' not implemented!")
		event.Skip()
	
	def do_comparison_default(self, event):  # wxGlade: Launcher.<event_handler>
		# Read settings
		self.significance_level_value.SetValue(str(self._parent.Config.comparison_a))
		self.comparison_alignment_Dw_value.SetValue(str(self._parent.Config.comparison_rt_modulation))
		self.comparison_alignment_Gw_value.SetValue(str(self._parent.Config.comparison_gap_penalty))
		self.comparison_alignment_min_peaks_value.SetValue(str(self._parent.Config.comparison_min_peaks))
		
		print("Event handler 'do_comparison_default' not implemented!")
		event.Skip()
	
	def do_comparison_reset(self, *args):  # wxGlade: Launcher.<event_handler>
		# Reset to default Settings
		Config = ConfigParser.ConfigParser()
		Config.read("lib/default.ini")
		
		self.significance_level_value.SetValue(Config.get("comparison", "a"))
		self.comparison_alignment_Dw_value.SetValue(Config.get("comparison", "rt_modulation"))
		self.comparison_alignment_Gw_value.SetValue(Config.get("comparison", "gap_penalty"))
		self.comparison_alignment_min_peaks_value.SetValue(Config.get("comparison", "min_peaks"))
	
	def comparison_show_box_whisker(self, event):
		self.ChartViewer = ChartViewer.ChartViewer(self, chart_type="box_whisker",
												   initial_samples=[self.comparison_left_project,
																	self.comparison_right_project],
												   )
		self.ChartViewer.Show()
		self.ChartViewer.Raise()
		event.Skip()
	
	def comparison_show_pca(self, event):
		self.ChartViewer = ChartViewer.ChartViewer(self, chart_type="pca",
												   initial_samples=[self.comparison_left_project,
																	self.comparison_right_project],
												   )
		self.ChartViewer.Show()
		self.ChartViewer.Raise()
		event.Skip()
	
	def comparison_show_radar(self, event):  # wxGlade: Launcher.<event_handler>
		self.ChartViewer = ChartViewer.ChartViewer(self, chart_type="radar",
												   initial_samples=[self.comparison_left_project,
																	self.comparison_right_project],
												   )
		self.ChartViewer.Show()
		self.ChartViewer.Raise()
		event.Skip()
	
	def comparison_show_mean_peak_area(self, event):  # wxGlade: Launcher.<event_handler>
		self.ChartViewer = ChartViewer.ChartViewer(self, chart_type="mean_peak_area",
												   initial_samples=[self.comparison_left_project,
																	self.comparison_right_project],
												   )
		self.ChartViewer.Show()
		self.ChartViewer.Raise()
		event.Skip()
	
	def OnComparisonLog(self, evt):
		self.comparison_log_text_control.AppendText(evt.log_text)

# end of class compare_tab
